name: Docker Image CI

on:
  push:
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install unittest-xml-reporting

      - name: Run tests
        run: python -m xmlrunner discover -s tests -o test-results

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: test-results/*.xml

  build-ets2:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Write VERSION file
        run: |
          touch VERSION
          echo "${{ github.ref_name || 'devel' }}" > VERSION
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            lshallo/ets2-convoy-server
            ghcr.io/lshallo/ets2-convoy-server

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_password }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ETS2 Convoy Server | Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-ats:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Write VERSION file
        run: |
          touch VERSION
          echo "${{ github.ref_name || 'devel' }}" > VERSION
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            lshallo/ats-convoy-server
            ghcr.io/lshallo/ats-convoy-server

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_password }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ATS Convoy Server | Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          build-args: |
            APP_ID=2239530
            SAVEGAME_LOCATION=/home/steam/.local/share/American Truck Simulator/
            EXECUTABLE=/app/bin/linux_x64/amtrucks_server
            DEFAULT_PACKAGES=default_packages/ats
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}